name: Get My Shader or Die Trying 🎮

on:
  workflow_dispatch: # این یعنی هر وقت خودت دکمه رو زدی اجرا بشه

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # برای اینکه اجازه داشته باشه فایل رو آپلود کنه

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download SEUS Shader
        run: |
          # با استفاده از curl فایل رو می‌کشیم بیرون
          # از -L استفاده می‌کنیم چون ریدایرکت زیاده، -o هم برای اسم فایل
          # یوزر ایجنت هم می‌زنیم که سایت فکر کنه ما یه مرورگرِ باکلاسیم، نه یه رباتِ گرسنه!
          curl -H "User-Agent: Mozilla/5.0" -L "https://www.sonicether.com/download/seus-renewed-v1-0-1/?wpdmdl=2144" -o "SEUS-Renewed-v1.0.1.zip"

      - name: Commit and Push
        run: |
          git config --global user.name "ShaderBot-2000"
          git config --global user.email "actions@github.com"
          git add SEUS-Renewed-v1.0.1.zip
          
          # چک می‌کنیم اگه فایل تغییر نکرده، الکی ارور نده
          git diff --quiet && git diff --staged --quiet || git commit -m "Add/Update SEUS Shader 1.18 directly from source"
          
          git push
